### ISSUE TITLE
Limit total number of word examples and phrases

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#100]
Currently, the backend will return all the examples and phrases associated with that word.

But as the number of phrases and examples associated with a word grows, we should limit the data that gets handed over to the client.

Limit a word's `examples` and `phrases` array down to 3.

**Comment by Ebugo** [comment]
Hi @ijemmao, Is anyone on this already or do I take it up?

**Comment by ijemmao** [comment]
@Ebugo Hey, yeah this ticket is actually outdated since we removed the concept of `Phrases`. You can pick up another ticket that you find interesting!

**Comment by Ebugo** [comment]
Okay, thanks. I'm now working on the web scraping issue.
