### ISSUE TITLE
Create /DELETE route for Words

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#131]
Currently, there are some duplicate words in the database, but there's no way to remove those words.

Create a new /DELETE route that a merger would use to delete a word document from the production database.

The route to implement would be DELETE `api/v1/edit/words/:id` which will allow for a single word document to be deleted.

**Comment by pappyJ** [comment]
Aye Captain

**Comment by oemekaogala** [comment]
Ill take this one

**Comment by ijemmao** [comment]
Closing this ticket since it's now outdated and the not the functionality needed for the API.
