### ISSUE TITLE
Create a subdomain for the docs

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#140]
Currently, the docs live on [http:///localhost:8080/docs](http://localhost:8080/docs) in a local server.

The docs should live on the subdomain `docs.localhost:8080` so when it gets deployed to production it should look like `docs.igboapi.com`

[This package](https://www.npmjs.com/package/express-subdomain) might be able to help with this ticket.

**Comment by ijemmao** [comment]
Closing this issue since there's no pressing need to use subdomains over routes.

**Comment by oemekaogala** [comment]
I think we should reopen this for the API. It would be nice to have our API contained in its own subdomain (api.igboapi.com), leaving igboapi.com to be the main website/landing page. This way we can build an online dictionary, docs (igboapi.com/docs), and more, but making requests via API will be super clean.
