### ISSUE TITLE
Frontend optimization 

### ISSUE THREAD

**Issue by Mancancode** [ijemmao/igbo_api#162]
Here our aim is to make the frontend more `beautiful `and `welcoming `for visitors by improving `typography `with the best `fonts`,  choosing better `colors  ` and `designs `that will blend with the `fonts`, and also add `images `if need be.

**Comment by ijemmao** [comment]
Are you planning on drafting up some designs first or jumping straight into making code changes?

**Comment by Mancancode** [comment]
Well drafting up designs would be cool, but I think we need to make some code changes first then see how it looks then , we can draft out better designs from there.

**Comment by ijemmao** [comment]
Closing this ticket since it's getting old.
