### ISSUE TITLE
Convert Dictionary JSON Files to MongoDB

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#20]
In order to make the search feature more scalable and easy to maintain, the data found in the dictionary JSON files need to be transferred into a MongoDB database.

Here are the current models that would be helpful:
* `Term`
  * Word Class
  * Definitions
  * List of `Phrase` documents
  * List of `Example` documents
  * **Dialect/Region**
* `Phrase`
  * Definition
  * List of `Example` documents
* `Example`
  * Textual example

**Note**: Terms in bold are still a work in progress and might not be included in the document

**Comment by ezesundayeze** [comment]
Hi, @ijemmao I found that this looks similar to this https://github.com/ijemmao/igbo_api/issues/41 which is in progress.

Is it intentional?

**Comment by ijemmao** [comment]
> Hi, @ijemmao I found that this looks similar to this #41 which is in progress.
> 
> Is it intentional?

Yeah, I had plans on closing this ticket since it's scope is too large for a PR. We can refer to #41 for the progress of moving the data in JSON object over to MongoDB
