### ISSUE TITLE
Use PM2 instead of Nodemon 

### ISSUE THREAD

**Issue by pappyJ** [ijemmao/igbo_api#204]
Use PM2 As the process management tool in development  environment .. Except you have special reasons for using nodemon as a core app dependency

**Comment by ijemmao** [comment]
I've never heard of PM2, what are some of it's immediate benefits?

**Comment by pappyJ** [comment]
It Is A Process Management tool just like nodemon but in production this time and it comes with other benefits too .. it is also mentioned in almost a every node js best practices article in the internet .. You Can Checkout Their website [here
![Screenshot from 2020-10-30 05-26-56](https://user-images.githubusercontent.com/65920240/97659949-95fd5900-1a70-11eb-9322-f849ed84974d.png)
](https://pm2.keymetrics.io/)

**Comment by ijemmao** [comment]
Yeah, I read through the site and I saw these features, which all seem pretty nice! But I was just wondering what cases have you come across while developing in this project that would immediately benefit from making the switch to PM2?

I ask this question to make sure that we aren't using technology for the sake of using technology. Making a switch to PM2 for development and even production purposes is a big transition. I want to make sure if we do move forward with this technology, we know what benefits we would see automatically. With that being said, could you share what benefits that we could immediate experience for this project if we made the switch?

**Comment by pappyJ** [comment]
It helps to 
1. Restart the app automatically if it crashes.
2. Gain insights into runtime performance and resource consumption.
3. Modify settings dynamically to improve performance.
4. Control clustering.(from a YouTube video I watched .. You can spwan another process if incoming requests are much and once the load reduces pm2 kills the process automatically)

It also has down sides ... Once you run pm2 command .. It actually runs in the background until you manually kill it.

Maybe I'll research more to convince you

**Comment by ijemmao** [comment]
@pappyJ What's the status of this issue?

**Comment by pappyJ** [comment]
Still on ma research .... Almost done I give final feedback ASAP

**Comment by ijemmao** [comment]
Closing this ticket since it's been inactive. Re-open the PR if there are any updates.
