### ISSUE TITLE
Dictionary Site

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#21]
Create a quick site that uses the API and displays the results.

**Comment by C-Zekeri** [comment]
Hi @ijemmao I'd love to work on this issue. Anything I should know before getting started?

**Comment by ijemmao** [comment]
> Hi @ijemmao I'd love to work on this issue. Anything I should know before getting started?

Amazing! Yeah, there's a few things that I was considering for this ticket:

* Use Gatsby to build the site - this will make it easier to customize the site and interface with the API
* Keep it in this repo - So the front-facing site code would live on it's own branch in this repo
* Use a CSS utility framework like [Tailwind](https://tailwindcss.com/) to keep everything looking consistent
* Follow the look of [Jisho](https://jisho.org/) where the search bar is on the home page, and then once you enter the term, you will get back it's word class, definition, phrases, and their examples.

These are super high levels and there's definitely details that need to be worked out, so please let me know if you have any questions. I recommend creating smaller tickets that focus on a particular part of building out the front-site so others can help out.

**Comment by C-Zekeri** [comment]
Ah. I've never actually worked with Gatsby before, so if that's a requirement I'm not sure I'll be able to pitch in.
Thank you 🤗

**Comment by ijemmao** [comment]
> Ah. I've never actually worked with Gatsby before, so if that's a requirement I'm not sure I'll be able to pitch in.
> Thank you 🤗

@C-Zekeri A lot of this is still up the air, so if there's a framework that you prefer using you can suggest it. But if you're not feeling up to it no worries! You can still put in feature requests for the API!

**Comment by C-Zekeri** [comment]
Alright then. On second thought, since I have a bit of React knowledge, I'd be willing to learn Gatsby for the project. The only thing is I might take a bit more time, but if you don't mind that, then I'll be glad to do so.

**Comment by ijemmao** [comment]
@C-Zekeri nice! In order to make this more manageable, I recommend making super small issues that break up the work that your going to be completing.

So a good first issue would be to create a new branch that's dedicated to the source code to hold the site and set up a basic Gatsby project there.

**Comment by C-Zekeri** [comment]
Alright, will get on it, thank you very much.

**Comment by C-Zekeri** [comment]
Hi @ijemmao. Are we also including an about page, or the lone home page with search results linking to a detail page?

**Comment by C-Zekeri** [comment]
Great. Thank you!

**Comment by Mancancode** [comment]
Hello I will be working on enhancing the frontend, my first step will make the search button to look for welcoming.

**Comment by ijemmao** [comment]
@Mancancode awesome! Could you create an issue that details what you're going to do exactly, and I can officially assign you to that ticket?

**Comment by ijemmao** [comment]
Closing this ticket since it's outdated and a good portion of what's been mentioned in this thread has been completed.
