### ISSUE TITLE
Create Igbo Part of Speech Tagset Constant

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#316]
## Background
In order for the API to capture the nuance of the Igbo language, it needs to have a part of speech annotating system that provides that nuance. We want to use this API to build treebanks for other projects to use

**Treebank** - A database of sentences that are annotated with syntactic information, often in the form of a tree.
## Feature
Use this [Igbo Part of Speech Tagset](https://www.sketchengine.eu/igbo-part-of-speech-tagset/) annotation system and create a new file called `WordClass` that exports a new object with the following structure

```
export default {
    CJN: {
         label: 'Conjuction',
         description: 'Conjunction'
    }
}
```
`label` should be a simplified label that most people would understand (in this case it's just Conjunction)
`description` should be the description found in the webpage's table

**Comment by Ebugo** [comment]
Okay, I'd need you to throw more light on your last sentence though... 

> label should be a simplified label that most people would understand (conjunction instead of coordinating conjunction
> description should be the description found in the webpage's table

**Comment by ijemmao** [comment]
If you take a look at the table, the first tag, for example, says 'Coordinating conjunction' which isn't something that a regular person will automatically understand. Instead, a person would relate more to just 'conjunction' since that's what they've been taught in school.

The `label` should be a simplified "description" of the `description`. In other words, `label` should use terminology that was taught in primary or secondary school, while the `description` is just copying the text found in the original table.

**Comment by Ebugo** [comment]
Oh, okay. More like exporting the already existing to something more familiar to the public...

**Comment by ijemmao** [comment]
@Ebugo Sort of, all you want to do though is create a new file called `WordClass.js` inside the `constants` directory. Inside this file, you should export by default an object with the structure that I detailed in the ticket.

So by the end of your work, you should have just created one new constants file.

**Comment by Ebugo** [comment]
oh, cool...Thanks for the clarity.
