### ISSUE TITLE
Validate wordClass fields with WordClass Constants

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#322]
**Is your feature request related to a problem? Please describe.**
Word documents can technically have any value living in their `wordClass` field. For example, a word document could look something like this:

```
{
    word: 'word',
    wordClass: 'adjective',
}

// or

{
    word: 'another word',
    wordClass: 'phrase',
}
```

Since `wordClass` can currently take any string value, that introduces the possibility of introducing inconsistent `wordClass` values which can lead to issues of sorting or filtering through all available word documents. If we look at the second wordDocument object, we can see that 'phrase' is assigned to `wordClass` even though 'phrase' isn't a valid `wordClass` value.

**Describe the solution you'd like**
Use the `WordClass.js` constants file to validate the `wordClass` values. This means, whenever a word document is about to be updated and saved using `mongoose` a check needs to occur to make sure  the value in `wordClass` should be a value found in `WordClass.js`

**Describe alternatives you've considered**
N/A

**Additional context**
Consider using [Mongoose Middleware](https://mongoosejs.com/docs/middleware.html) which can run before a `mongoose` action call. So in a before hook, you can validate the value in the word document that's about to be saved to make sure that it has a valid WordClass value.

**Comment by Ebugo** [comment]
Okay. Working on this now.

**Comment by ijemmao** [comment]
This ticket is no longer needed
