### ISSUE TITLE
Filtering Part of Speech

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#363]
**Is your feature request related to a problem? Please describe.**
A new `wordClass` param should be handled by the backend that allows users to search for keywords that are only the specified `wordClass`.

**Describe the solution you'd like**
1. Handle a new param called `wordClass` that's expected to take in one of the `WordClass.js` values (for example, `NNC` or `CJN`) and filter word results
2. Create tests to make sure that this functionality works as expected

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Robertito1** [comment]
Just started working on this
