### ISSUE TITLE
"Dark mode"

### ISSUE THREAD

**Issue by Effiti** [ijemmao/igbo_api#374]
**Is your feature request related to a problem? Please describe.**
A darkmode is common on modern sites.

**Describe the solution you'd like**
Add a switch to controll the appeareance. Idealy, the theme would be stored in a cookie. As a background colour, the background colour of the footer could be used. Add a test to test-homepage.js to test the behaviour. 

**Describe alternatives you've considered**
To avoid cookie usage, the appeareance could also be stored in a URL parameter.

**Comment by ijemmao** [comment]
@Effiti I think that cookies or localStorage should be used instead of adding this information to the URL so that the URL doesn't get cluttered with state

**Comment by inezabonte** [comment]
I'd suggest [next-themes](https://www.npmjs.com/package/next-themes) it covers the local storage stuff for you and also comes with a hook that can be used to check the state which you can use to display a different toggle icon depending on the current theme

**Comment by jovialcore** [comment]
Alright. I'm taking this one. I'm implementing this feature!

**Comment by ijemmao** [comment]
@Effiti @jovialcore Any updates on the progress for this ticket?

**Comment by Effiti** [comment]
> @Effiti @jovialcore Any updates on the progress for this ticket?

Thought @jovialcore was on it

**Comment by ijemmao** [comment]
@Effiti @jovialcore I'm planning on closing this ticket since it's become two weeks old. Feel free to reopen this ticket if you are planning on it yourself. If you do reopen the ticket, comment that you are working on it so everyone knows the ticket's status.
