### ISSUE TITLE
Add a Link to the Repo Wiki Page

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#378]
**Is your feature request related to a problem? Please describe.**
I just added some documentation on the Wiki page, so the README.md should link to it.

**Describe the solution you'd like**
Make the following change

```diff
- Contribution | Code of Conduct | Slack Channel
+ Contribution | Documentation | Code of Conduct | Slack Channel
```

* The link for `Documentation` should be: https://github.com/ijemmao/igbo_api/wiki
* Delete [`Android_README.md`](https://github.com/ijemmao/igbo_api/blob/master/Android_README.md) since it's been moved over to the Wiki page

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by inezabonte** [comment]
I'd like to work on this 🙂

**Comment by ijemmao** [comment]
@inezabonte Go for it! Just link to this issue in your PR so that we can track the progress
