### ISSUE TITLE
Separate About and contact section 

### ISSUE THREAD

**Issue by inezabonte** [ijemmao/igbo_api#386]
**Describe the bug**
On the about page the `About` and  `Contact` section are very close together. 
Almost look as if it's one sentence

**To Reproduce**
1. Go to https://igboapi.com/about

**Expected behavior**
The two sections should have enough space between them to easily tell them apart

**Screenshots**
<img width="1648" alt="Screen Shot 2021-06-23 at 16 32 13" src="https://user-images.githubusercontent.com/33348046/123116228-04988800-d441-11eb-8ddc-d5c123795ee5.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 11.2.3

**Comment by inezabonte** [comment]
@ijemmao I'd like to work on this if it's okay

**Comment by ijemmao** [comment]
@inezabonte I'm confused what this ticket would be addressing 😅 Under the expected behavior section, you restate the problem that you've noticed.

**Comment by inezabonte** [comment]
Sorry about that @ijemmao fixed

**Comment by ijemmao** [comment]
@inezabonte If you haven't started already, feel free to get started!
