### ISSUE TITLE
Upgrade to Nextjs 11

### ISSUE THREAD

**Issue by inezabonte** [ijemmao/igbo_api#388]
**Is your feature request related to a problem? Please describe.**
Currently this repo is using Next.js 9.5.5 which is quite outdated considering the new features that
have come out over the past few years such as the custom Link component that make client-side navigation 
way faster.

**Describe the solution you'd like**
Upgrade current Next.js package to the latest version

**Comment by ijemmao** [comment]
@inezabonte When you save "that makes client-side navigation way faster", what do you mean by faster? Is it from a performance standpoint that users will notice or from a developer standpoint of making it easier to work with navigation?

I ask because upgrading multiple major versions in one go comes with risks since there are certain features that are not backwards compatible.

**Comment by inezabonte** [comment]
From a perfomance standpoint it will be faster. The Link component from Next.js enables client-side navigation instead of sending requests to the server every time you visit a page. So it is notably faster. [Link](https://nextjs.org/docs/api-reference/next/link)

I do understand having a project as big as this it may not be an easy task.

**Comment by ijemmao** [comment]
@inezabonte Are there other features that you're expecting to introduce to this project from updating the Nextjs version to 11?

**Comment by inezabonte** [comment]
Apart from the ones I mentioned I think those are some of the issues I noticed while looking at the project.
Otherwise I don't think there should be any breaking changes.

**Comment by inezabonte** [comment]
You can also do it progressively by upgrading first to nextjs 10 as the features are slowly added
To make sure you don't break the project. Because it might require some refactoring

**Comment by ijemmao** [comment]
@inezabonte I'm planning on closing this issue unless there's a PR coming soon. Let me know!

**Comment by inezabonte** [comment]
It can be closed for now @ijemmao
