### ISSUE TITLE
Add Build Status Badge to README

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#39]
Add a small Build Status badge right below the title of the README

This repo is a good place to see how to add a badge - https://github.com/CultureHQ/github-actions-badge
This Medium guide is pretty helpful - https://medium.com/@AndreSand/adding-github-action-workflow-status-badge-to-your-repository-22ccea025af6

**Comment by namit-chandwani** [comment]
Hey, I'd like to work on this issue.
