### ISSUE TITLE
Scrape 1000 Most Common Igbo Words

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#66]
Scrape the data that's found in this site and append it to the JSON dictionary objects.

https://1000mostcommonwords.com/1000-most-common-igbo-words/

If the word doesn't exist in the JSON dictionary, create a new object where that object has `definitions, word, wordClass, phrases, examples, and variations`.

If the word already exists in the JSON dictionary, append that information.

**Comment by pappyJ** [comment]
![Screenshot from 2020-10-09 14-24-14](https://user-images.githubusercontent.com/65920240/95588504-69d75500-0a3b-11eb-96fb-13f30c924fdf.png)

I Scrapped D Data Using My Little Experiernce... Does The Data Need Additional fields ???...

**Comment by ijemmao** [comment]
@pappyJ wowow this is awesome! Yeah, what you want to do is that you want to include the logic that you wrote that managed to create this `words.json` object and incorporate it into the main codebase.

The script that you wrote could probably live in the `dictionaries` directory, and then you can name the JSON file that you've created as `ig-en-1000-common.js`.

Also, could you change the `meaning` key to `definition` so that it follows the current data structure as close as possible?

**Comment by pappyJ** [comment]
Thanks ma'am .. I'll it give my best shot

**Comment by ijemmao** [comment]
Let me know if you have more questions!

**Comment by pappyJ** [comment]
Sure

**Comment by pappyJ** [comment]
![Screenshot from 2020-10-10 08-22-53](https://user-images.githubusercontent.com/65920240/95648794-e4eb4a80-0ad1-11eb-8c49-60d6058dc51e.png)
How About this Structure???

**Comment by pappyJ** [comment]
![Screenshot from 2020-10-10 08-34-06](https://user-images.githubusercontent.com/65920240/95649032-67283e80-0ad3-11eb-97fb-27d62f86cda0.png)

Made Some Changes to fit d base dictionary pattern .. Check for any required changes so i make some code refactor and create a PR

**Comment by ijemmao** [comment]
@pappyJ This looks perfect.

All I would say is to make sure that you include both the script that was able to create this `json` file and the `json` file itself in the main project codebase so that in a future ticket, we can try to merge `ig-en-1000-common.json` with our `ig-en.json` and `ig-en_expanded.json` dictionaries.

**Comment by pappyJ** [comment]
OKk

**Comment by ijemmao** [comment]
Closed by #133
