### ISSUE TITLE
Scrape Terms from Igbo English Website

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#67]
Scrape the Igbo terms along with their information from this site:

http://www.igboenglish.com/

The data that gets scrapped and parsed should be appended to the JSON dictionary objects.

**Comment by uzukwujp** [comment]
I started working on this project today

**Comment by Ebugo** [comment]
Hi, I'm still waiting for your decision on splitting this so we don't have conflicting contributions. Thanks.

**Comment by ijemmao** [comment]
@uzukwujp would know the status of this ticket.

**Comment by Ebugo** [comment]
Okay, thanks.

**Comment by ijemmao** [comment]
@Ebugo @uzukwujp Do you two have any updates for this issue? Do you need some help?

**Comment by Ebugo** [comment]
Yeah, a rather brief update.
The website is really so poorly formatted and makes scraping a lot harder than it should be. I'm working around it though, and should come up with something shortly.

**Comment by ijemmao** [comment]
This ticket is now out of date, it will be closed.
