### ISSUE TITLE
Initial setup for the front facing site

### ISSUE THREAD

**Issue by C-Zekeri** [ijemmao/igbo_api#68]
Create a new branch dedicated to the source code for the front facing site discussed in #21. Setup a basic Gatsby project in this branch.

**Comment by ijemmao** [comment]
@C-Zekeri Here's the branch I mentioned - https://github.com/ijemmao/igbo_api/tree/gatsby-dev

**Comment by C-Zekeri** [comment]
Oh great. This makes it easier, thank you. I'll work on these. Should I also create issues for these?

**Comment by ijemmao** [comment]
> Oh great. This makes it easier, thank you. I'll work on these. Should I also create issues for these?

Yeah please do! You can create an issue for each of these so that others can help you work on the front site.
