### ISSUE TITLE
Basic English to Igbo Search Functionality

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#7]
Currently, the API allows for Igbo to English search, but to further expand what this API can do it needs to have an English to Igbo search capability.

This issue doesn't focus on implementing a full fledge English to Igbo, instead the main focus is to lay down the ground work for future related features.

**Comment by ezesundayeze** [comment]
I am wondering if there is a contributor's guide. We've got a route structure like this -> `http://localhost:8080/api/v1/search/words?keyword=agụū` for the igbo, right? I think the route structure needs to be redesign in a way to accommodate English-Igbo, Igbo-English

Maybe something like `http://localhost:8080/api/v1/search/en-igbo/words?keyword=agụū` and can be switched vice versa 
- en-igbo
- igbo-en

What do you think?

**Comment by ijemmao** [comment]
> I am wondering if there is a contributor's guide. We've got a route structure like this -> `http://localhost:8080/api/v1/search/words?keyword=agụū` for the igbo, right? I think the route structure needs to be redesign in a way to accommodate English-Igbo, Igbo-English
> 
> Maybe something like `http://localhost:8080/api/v1/search/en-igbo/words?keyword=hunger` and can be switched vice versa 
> - en-igbo
> - igbo-en
> 
> What do you think @ijemmao ?

@ezesundayeze 100% agree on creating a Contributor's guide to make this more accessible to people. I'll make it within the next few days.

I've been modeling the user experience off of what my favorite Japanese-English dictionary - https://jisho.org/

Notice how the route structure doesn't change when you request the Japanese word using Romantic characters vs using the original Japanese characters.

But for now, I do agree with having two separate routes. Doing that will help separate out the work that needs to be done.

The hardest part of this issue is that we need to come up with a smart way to reverse index terms based on the English instead of the Igbo.

Do you have any ideas of how we would want to structure our data to make it easier to search using English?

**Comment by ezesundayeze** [comment]
> Notice how the route structure doesn't change when you request the Japanese word using Romantic characters vs using the original Japanese characters.

Yea, right.

> The hardest part of this issue is that we need to come up with a smart way to reverse index terms based on the English instead of the Igbo. Do you have any ideas of how we would want to structure our data to make it easier to search using English?

I will have to check in with this, let's see.

**Comment by ijemmao** [comment]
> > The hardest part of this issue is that we need to come up with a smart way to reverse index terms based on the English instead of the Igbo. Do you have any ideas of how we would want to structure our data to make it easier to search using English?
> 
> I can only remember doing that tokenisation and reverse index thing in my NLP class 😊 . Will have to check in again.

Please let me know what you find! I'm going to start this ticket. I'm planning on achieving basic functionality, so nothing to too crazy. If there's a feature that you want to see from this API let me know!
