### ISSUE TITLE
Organise output of search response in demo site

### ISSUE THREAD

**Issue by C-Zekeri** [ijemmao/igbo_api#82]
The demo site (see #21 ) set up [here](https://github.com/ijemmao/igbo_api/tree/gatsby-dev) already has an axios request implemented to query the API and display results, but the results have still not been organised or styled.

Note: This project is built with Gatsby and uses [Tailwind](https://tailwindcss.com/) utility classes in order to give a consistent look to the site.

**Comment by ijemmao** [comment]
@C-Zekeri Is this ticket still something we should work on?

**Comment by ijemmao** [comment]
Closing this ticket since it's outdated.
