### ISSUE TITLE
Create Separate Usage Docs

### ISSUE THREAD

**Issue by ijemmao** [ijemmao/igbo_api#92]
Currently, all the documentation on how to interact with the API is in the README.

That information should be moved out to its own doc. Maybe a USAGE.md file or create a new page in the Wiki.

Maybe we explore using automatically generating API docs with packages like [apidoc](https://www.npmjs.com/package/apidoc)

**Comment by oemekaogala** [comment]
I can take a stab at this!

**Comment by ijemmao** [comment]
This ticket has been addressed by the linked PR.
